# Generated by Django 4.0.4 on 2022-05-06 07:52

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('departmentorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IssuingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('totalamount_currency', djmoney.models.fields.CurrencyField(choices=[('LKR', 'Rs')], default='XYZ', editable=False, max_length=3)),
                ('totalamount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('discountratio_currency', djmoney.models.fields.CurrencyField(choices=[('LKR', 'Rs')], default='XYZ', editable=False, max_length=3)),
                ('discountratio', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('netamount_currency', djmoney.models.fields.CurrencyField(choices=[('LKR', 'Rs')], default='XYZ', editable=False, max_length=3)),
                ('netamount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('iodate', models.DateField(auto_now=True)),
                ('notes', models.TextField()),
                ('departmentorder', models.ForeignKey(db_column='departmentorder_id', on_delete=django.db.models.deletion.CASCADE, to='departmentorder.departmentorder')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employee.new')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuingorder.status')),
            ],
        ),
    ]
