# Generated by Django 4.0.4 on 2022-05-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_category'),
        ('issuingorder', '0002_alter_issuingorder_iodate'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuingorder',
            name='item',
            field=models.ManyToManyField(to='item.item'),
        ),
    ]
