# Generated by Django 4.0.4 on 2022-05-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuingorder', '0003_issuingorder_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuingorder',
            name='item',
        ),
    ]
