# Generated by Django 4.0.4 on 2022-05-24 17:29

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_options'),
        ('issuingorder', '0004_remove_issuingorder_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('salesprice_currency', djmoney.models.fields.CurrencyField(choices=[('LKR', 'Rs')], default='XYZ', editable=False, max_length=3)),
                ('salesprice', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('linetotal_currency', djmoney.models.fields.CurrencyField(choices=[('LKR', 'Rs')], default='XYZ', editable=False, max_length=3)),
                ('linetotal', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='issuingorder',
            name='item',
            field=models.ManyToManyField(through='issuingorder.IssuingItem', to='item.item'),
        ),
        migrations.AddField(
            model_name='issuingitem',
            name='issuingorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuingorder.issuingorder'),
        ),
        migrations.AddField(
            model_name='issuingitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
        migrations.AlterUniqueTogether(
            name='issuingitem',
            unique_together={('item', 'issuingorder')},
        ),
    ]
