# Generated by Django 4.0.4 on 2022-05-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_options'),
        ('issuingorder', '0004_remove_issuingorder_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuingorder',
            name='item',
            field=models.ManyToManyField(to='item.item'),
        ),
    ]
