# Generated by Django 4.0.4 on 2022-05-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotationrequest', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('validatefrom', models.DateField()),
                ('validateto', models.DateField()),
                ('notes', models.TextField()),
                ('regdate', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.new')),
                ('quotationrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotationrequest.quotationrequest')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.status')),
            ],
        ),
    ]
