# Generated by Django 4.0.4 on 2022-05-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(to='item.brand'),
        ),
    ]
