# Generated by Django 4.0.4 on 2022-05-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('item', '0005_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
