# Generated by Django 4.0.4 on 2022-05-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('item', '0006_item_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
