# Generated by Django 4.0.4 on 2022-04-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiviStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=200)),
                ('callingname', models.CharField(max_length=75)),
                ('photo', models.ImageField(upload_to='')),
                ('nic', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=10)),
                ('land', models.CharField(max_length=10)),
                ('notes', models.TextField()),
                ('regdate', models.DateField(auto_now=True)),
                ('civilstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.civistatus')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.designation')),
                ('employeestatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.status')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.gender')),
            ],
        ),
    ]
