# Generated by Django 4.0.4 on 2022-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='number',
            field=models.CharField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=10, unique=True),
        ),
    ]
