# Generated by Django 4.0.3 on 2022-03-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Main',
        ),
        migrations.RenameModel(
            old_name='EmployeeStatus',
            new_name='Status',
        ),
    ]
