# Generated by Django 4.0.3 on 2022-03-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employee_main_rename_employeestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='civilstatus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.civistatus'),
        ),
        migrations.AlterField(
            model_name='main',
            name='designation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.designation'),
        ),
        migrations.AlterField(
            model_name='main',
            name='employeestatus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.status'),
        ),
        migrations.AlterField(
            model_name='main',
            name='gender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.gender'),
        ),
    ]
