# Generated by Django 4.0.4 on 2022-04-23 17:15

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('land', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('cpname', models.CharField(max_length=254)),
                ('cpnumber', models.CharField(max_length=10)),
                ('creditlimit_currency', djmoney.models.fields.CurrencyField(choices=[('LKR', 'Rs')], default='XYZ', editable=False, max_length=3)),
                ('creditlimit', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('tobepaid_currency', djmoney.models.fields.CurrencyField(choices=[('LKR', 'Rs')], default='XYZ', editable=False, max_length=3)),
                ('tobepaid', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('remarks', models.TextField()),
                ('regdate', models.DateField(auto_now=True)),
                ('bhname', models.CharField(max_length=200)),
                ('baccountno', models.PositiveIntegerField()),
                ('bbranch', models.CharField(max_length=200)),
                ('bankname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.bank')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employee.new')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.status')),
            ],
        ),
    ]
