# Generated by Django 4.0.4 on 2022-04-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bankname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.bank'),
        ),
    ]
