# Generated by Django 4.0.4 on 2022-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_options'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='item',
            field=models.ManyToManyField(to='item.item'),
        ),
    ]
