# Generated by Django 4.0.4 on 2022-04-23 17:16

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('totalamount_currency', djmoney.models.fields.CurrencyField(choices=[('LKR', 'Rs')], default='XYZ', editable=False, max_length=3)),
                ('totalamount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField()),
                ('regdate', models.DateField(auto_now=True)),
                ('department', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentorder.status')),
            ],
        ),
    ]
