# Generated by Django 4.0.4 on 2022-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentorder',
            name='orderdate',
            field=models.DateField(),
        ),
    ]
