# Generated by Django 4.0.4 on 2022-04-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_designation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staus', models.BooleanField()),
                ('displayname', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('employee', models.ForeignKey(db_column='number', on_delete=django.db.models.deletion.CASCADE, to='employee.new')),
                ('role', models.ManyToManyField(to='user.role')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
